### ISSUE TITLE
Latest Gruvbox Theme 0.2.1 is incompatible with  IDEA 2020.1 

### ISSUE THREAD

**Issue by larrynikx** [Vincent-P/gruvbox-intellij-theme#19] opened 2020-04-12 17:06 UTC
**Short Description**
IDEA plugin is incompatible therefore the theme can not be applied.

**Steps to Reproduce**
Update IDEA to 2020.1

**Comment by Vincent-P** [comment] 2020-04-12 17:08
Duplicate of #16

**Closed as completed by Vincent-P** 2020-04-12 17:08 UTC

**Comment by stephanoparaskeva** [comment] 2020-04-12 19:30
This was closed as a duplicate of #16 but #16 was also closed referencing this. Does that mean the issue was resolved?
