### ISSUE TITLE
 Cursor appears below prompt in PyCharm Python Console

### ISSUE THREAD

**Issue by a3lem** [Vincent-P/gruvbox-intellij-theme#29] opened 2020-05-17 10:28 UTC
Hi there. Thanks for the great plugin. I'm pretty late to the Gruvbox party, but it's quickly becoming my favorite theme – especially with the addition of multiple variants to choose from.

I've noticed some surprising behavior when using Pycharm's Python Console with the plugin enabled: the cursor does not appear next to the IPython prompt, but two lines below the point where the prompt ends. None of the other theme plugins that I've tested (default and third-party) cause this behavior, which leads me to assume that we're dealing with a bug here.

Interestingly, an identical issue has been open at caleb/gruvbox-idea#20 since late 2018. It hasn't received any response there.

**Comment by Zackhardtoname** [comment] 2020-06-09 22:18
It's a pretty critical issue.
I think the problem is that the prompt sign is missing. There's is no way for me to tell if my code is done or not.

I have gone back to default because of this. Hope this gets resolved.

**Comment by Vincent-P** [comment] 2020-06-12 11:30
It should be fixed with #33.

**Closed as completed by Vincent-P** 2020-06-12 11:30 UTC
